#!/bin/bash

set -e

test -n "${NEXTCLOUD_USER}"
test -n "${NEXTCLOUD_PASSWORD}"
test -n "${NEXTCLOUD_DB}"

psql --variable ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-SQL
    CREATE USER $NEXTCLOUD_USER WITH PASSWORD '$NEXTCLOUD_PASSWORD';
    CREATE DATABASE $NEXTCLOUD_DB;
    GRANT ALL PRIVILEGES ON DATABASE $NEXTCLOUD_DB TO $NEXTCLOUD_USER;
SQL
